apiVersion: apps/v1
kind: Deployment
metadata:
  name: loopback-deployment
  labels: 
    app: loopback
spec:
  selector:
    matchLabels:
      app: loopback
  replicas: 1
  template:
    metadata:
      labels:
        app: loopback
    spec:
      containers:
      - name: loopback-app
        image: artijain/loopbackassisgnment:loop
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: loopback-svc
  labels:
    app: loopback
spec:
  ports:
    - port: 3000
  selector:
    app: loopback
  type: LoadBalancer  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lb-ingress-https
  labels:
    app: loopback
  annotations:
spec:
  rules:
  - http:
      paths:
      - path: /testapp
        pathType: Prefix
        backend:
          service:
            name: loopback-svc
            port:
              number: 3000


