apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: mysql-pass
  literals: 
  - username=mysql-pass
  - password=password

resources:
- mysql-deployment.yaml
- wordpress-deployment.yaml  